spring:
  application:
    name: zuul
  cloud:
    connfig:
      overrider-none: true
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
zuul:
  routes:
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/**
  retryable: true #启用重试
  
ribbon:
  MaxAutoRetries: 1
  
item-service:
  ribbon:
    MaxAutoRetriesNextServer: 2
   
management:
  endpoints:
    web:
      exposure:
        include:  hystrix.stream
